resolver 127.0.0.11 valid=5s;

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        resolver 127.0.0.11 valid=5s;
        proxy_pass http://ppm-backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 5s;
        proxy_next_upstream error timeout invalid_header http_502 http_503;
        client_max_body_size 20M;
    }
}